bertbot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
    path('history', views.history, name="history"),
]

main/models.py
from django.db import models


class Question(models.Model):
    question = models.TextField(null=False)
    wiki_terms = models.CharField(max_length=200, null=False)
    wiki_text = models.TextField(null=False)
    answer = models.CharField(max_length=200)
    prediction_score = models.FloatField(default=0)

main/forms.py
from django import forms
from .models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question', 'wiki_terms']

main/views.py
from django.shortcuts import render
from django.conf import settings
from .models import Question
from .forms import QuestionForm
import wikipediaapi


def index(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            try:
                question = form.cleaned_data['question']
                wiki_terms = form.cleaned_data['wiki_terms']
                wiki = wikipediaapi.Wikipedia('en')
                wiki_text = wiki.page(wiki_terms).summary

                result = settings.BERT_PIPELINE(question=question, context=wiki_text)
                answer = result['answer']
                prediction_score = result['score']

                q = Question()
                q.wiki_terms = wiki_terms
                q.wiki_text = wiki_text
                q.question = question
                q.answer = answer
                q.prediction_score = prediction_score
                q.save()
            except:
                answer = 'There was an error!'
                prediction_score = 0
        return render(request, 'main/index.html', {'form': form, 'answer': answer, 'score': prediction_score})
    else:
        form = QuestionForm()
        return render(request, 'main/index.html', {'form': form})


def history(request):
    q = Question.objects.all()
    return render(request, 'main/history.html', {'question': q})

main/templates/main/history.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>History</title>
  <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body style="max-width: 80%; margin: 0 auto;">

  <div class="history-header">
      <h2 id="history-title">History</h2>
      <p>History of questions and answers</p>
  </div>

  <a href="{% url 'main:index' %}">Back</a>

  {% for q in question %}
    <div class="card">
      <h3>{{ q.question }}</h3>
      <p><b>Terms:</b> {{ q.wiki_terms }}</p>
      <p><b>Context:</b> {{ q.wiki_text }}</p>
      <p><b>Answer:</b> {{ q.answer }}</p>
      <p><b>Score:</b> {{ q.prediction_score | floatformat:2 }}</p>
    </div>
  {% endfor %}

</body>
</html>

main/templates/main/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BERTBot</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
  <h1>BERTBot</h1>

    <div class="content">
        <form action="{% url 'main:index' %}" method="post">
            {% csrf_token %}
            <h2>Ask BERTBot</h2>
            <p>Question</p>
            {{ form.question }}
            <p>Wiki terms</p>
            {{ form.wiki_terms }}
            <div class="btn-block">
                <button type="submit">Submit</button>
            </div>
        </form>

        <div class="result">
            <h2>Result</h2>
            <p><b>Answer:</b> {{ answer }}</p>
            <p><b>Prediction score:</b> {{ score | floatformat:2 }}</p>
            <a href="{% url 'main:history' %}">History</a>
        </div>

    </div>




</body>
</html>